---  #test playbook
- hosts: linuxtest2
  remote_user: root
  tasks:
   - name: install docker-ce package
     yum: name=docker-ce state=present
   - name: copy docker-compose file
     copy: src=/home/wangqi/Downloads/docker-compose dest=/usr/local/bin/ mode='0755'
   - name: copy to-do app
     copy: src=/home/wangqi/Downloads/app.tar dest=/home/wangqi/Downloads/
   - name: start docker
     service: name=docker state=started
   - name: copy node image
     copy: src=/home/wangqi/Downloads/node.tar dest=/home/wangqi/Downloads/
   - name: load node image
     shell: docker load -i /home/wangqi/Downloads/node.tar
   - name: copy mysql image
     copy: src=/home/wangqi/Downloads/mysql.tar dest=/home/wangqi/Downloads/
   - name: load mysql image
     shell: docker load -i /home/wangqi/Downloads/mysql.tar
   - name: unzip app.tar
     shell: cd /home/wangqi/Downloads/ && tar -xvf app.tar
   - name: run app with docker-compose
     shell: cd /home/wangqi/Downloads/app && docker-compose up -d
